language: clojure
jdk:
  - oraclejdk8
lein: 2.7.1
env:
  - TZ=America/Chicago
script:
  - lein with-profile test cloverage --coveralls
  - curl -F 'json_file=@target/coverage/coveralls.json' 'https://coveralls.io/api/v1/jobs'
